"""
Tests for render_pipeline_md / render_handoff_md.

Run: python3 -m unittest tests.test_render
"""

import os
import sqlite3
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from db import db as dbmod


class RenderTests(unittest.TestCase):
    """Each test isolates the global DB_PATH onto a temp file."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self._orig_db = dbmod.DB_PATH
        self._orig_pipeline = dbmod.PIPELINE_MD_PATH
        self._orig_handoff = dbmod.HANDOFF_MD_PATH
        dbmod.DB_PATH = os.path.join(self.tmp.name, "test.db")
        dbmod.PIPELINE_MD_PATH = os.path.join(self.tmp.name, "pipeline.md")
        dbmod.HANDOFF_MD_PATH = os.path.join(self.tmp.name, "HANDOFF.md")
        dbmod._schema_ensured = False  # force re-init on first con()
        dbmod._apply_migrations(verbose=False)

    def tearDown(self):
        dbmod.DB_PATH = self._orig_db
        dbmod.PIPELINE_MD_PATH = self._orig_pipeline
        dbmod.HANDOFF_MD_PATH = self._orig_handoff
        dbmod._schema_ensured = False
        self.tmp.cleanup()

    def _read(self, path):
        with open(path) as f:
            return f.read()

    # ── tests ──────────────────────────────────────────────────────────────

    def test_empty_db_renders_well_formed_files(self):
        p = dbmod.render_pipeline_md()
        h = dbmod.render_handoff_md()
        ptext = self._read(p)
        htext = self._read(h)

        # Both files must lead with the do-not-hand-edit marker.
        self.assertTrue(ptext.startswith("<!-- AUTOGENERATED"))
        self.assertTrue(htext.startswith("<!-- AUTOGENERATED"))
        self.assertIn("do not hand-edit", ptext)
        self.assertIn("do not hand-edit", htext)

        # Empty-state copy.
        self.assertIn("No active roles.", ptext)
        self.assertIn("_None._", htext)
        self.assertIn("No analyses generated yet.", htext)

    def test_seeded_pipeline_md_includes_role_data(self):
        rid = dbmod.add_role("Acme", "Sr PM, Platform", tech_fit=8, culture_fit=7,
                             overall_fit=7.6, remote="Remote",
                             next_action="Run company-research",
                             next_action_due="2026-05-02")
        dbmod.add_role("Beacon", "Senior PM", overall_fit=4.0)
        dbmod.disqualify(rid + 1, reason="Below 6 — adjacent domain")
        dbmod.log_search_run(queries_run=8, roles_found=14, roles_added=2,
                             roles_duped=4, roles_screened=8)

        p = dbmod.render_pipeline_md()
        text = self._read(p)

        self.assertIn("Acme", text)
        self.assertIn("Sr PM, Platform", text)
        self.assertIn("Run company-research", text)
        self.assertIn("Beacon", text)
        self.assertIn("Below 6 — adjacent domain", text)
        self.assertIn("queries", text.lower())
        self.assertIn("Average fit (active)", text)

    def test_handoff_groups_by_status_and_lists_decisions(self):
        rid = dbmod.add_role("Acme", "Sr PM, Platform", overall_fit=7.6)
        dbmod.add_session_note("decision",
                               "Comp band not confirmed; ask candidate.",
                               role_id=rid)
        dbmod.add_session_note("completion",
                               "Drafted bullets; awaiting candidate confirmation.")

        h = dbmod.render_handoff_md()
        text = self._read(h)

        self.assertIn("### Researching (1)", text)
        self.assertIn("Acme", text)
        # Open decision should appear with the role context.
        self.assertIn("Comp band not confirmed", text)
        self.assertIn("Acme", text.split("Open Decisions")[1])
        # Recent completion should be rendered.
        self.assertIn("Drafted bullets", text)

    def test_resolved_decisions_are_not_rendered(self):
        rid = dbmod.add_role("Acme", "Sr PM, Platform")
        nid = dbmod.add_session_note("decision",
                                     "Outstanding question",
                                     role_id=rid)
        dbmod.resolve_session_note(nid, resolution="Confirmed by candidate")

        h = dbmod.render_handoff_md()
        text = self._read(h)
        decisions_block = text.split("Open Decisions")[1].split("Recent Session")[0]
        self.assertIn("_None._", decisions_block)
        self.assertNotIn("Outstanding question", decisions_block)

    def test_render_is_deterministic_modulo_timestamp(self):
        dbmod.add_role("Acme", "Sr PM, Platform", overall_fit=7.6)
        p = dbmod.render_pipeline_md()
        first = self._read(p)
        p = dbmod.render_pipeline_md()
        second = self._read(p)
        # Strip the timestamps and compare. Both the autogen header and the
        # "Last rendered" line carry timestamps.
        def strip(t):
            out = []
            for line in t.splitlines():
                if "AUTOGENERATED from" in line or "Last rendered" in line:
                    continue
                out.append(line)
            return "\n".join(out)
        self.assertEqual(strip(first), strip(second))

    def test_no_op_rerender_does_not_touch_file(self):
        """A second render against an unchanged DB must leave the file alone.

        Regression guard for the SessionStart-hook churn: every session
        start re-rendered the file with a fresh timestamp, producing a no-op
        diff that polluted `git status`. _write_render_if_changed should
        skip the write when only the timestamps would differ.
        """
        dbmod.add_role("Acme", "Sr PM, Platform", overall_fit=7.6)
        p = dbmod.render_pipeline_md()
        h = dbmod.render_handoff_md()
        mtime_p = os.path.getmtime(p)
        mtime_h = os.path.getmtime(h)
        first_p = self._read(p)
        first_h = self._read(h)

        # Wait long enough that a write would produce a different mtime,
        # then re-render. The file must NOT be rewritten.
        import time
        time.sleep(1.1)
        dbmod.render_pipeline_md()
        dbmod.render_handoff_md()

        self.assertEqual(os.path.getmtime(p), mtime_p,
                         "pipeline.md was rewritten despite no DB change")
        self.assertEqual(os.path.getmtime(h), mtime_h,
                         "HANDOFF.md was rewritten despite no DB change")
        self.assertEqual(self._read(p), first_p)
        self.assertEqual(self._read(h), first_h)

    def test_rerender_writes_when_db_changes(self):
        """Inverse of the no-op guard — a real DB change must hit the file."""
        rid = dbmod.add_role("Acme", "Sr PM, Platform", overall_fit=7.6)
        p = dbmod.render_pipeline_md()
        first = self._read(p)

        dbmod.update_status(rid, "Qualified", note="Looks good")
        dbmod.render_pipeline_md()
        second = self._read(p)

        self.assertNotEqual(first, second)
        self.assertIn("Qualified", second)

    def test_analyses_index_groups_by_role(self):
        r1 = dbmod.add_role("Acme", "Sr PM, Platform")
        r2 = dbmod.add_role("Beacon", "Senior PM")
        dbmod.log_analysis(role_id=r1, skill_type="analyze-jd",
                           file_path="references/analyses/r1-jd.md",
                           overall_fit=7.6, verdict="pursue")
        dbmod.log_analysis(role_id=r1, skill_type="company-research",
                           file_path="references/analyses/r1-research.md")
        dbmod.log_analysis(role_id=r2, skill_type="analyze-jd",
                           file_path="references/analyses/r2-jd.md",
                           overall_fit=6.2, verdict="research")

        h = dbmod.render_handoff_md()
        text = self._read(h)
        self.assertIn(f"### role id={r1}", text)
        self.assertIn(f"### role id={r2}", text)
        self.assertIn("references/analyses/r1-jd.md", text)
        self.assertIn("references/analyses/r2-jd.md", text)


if __name__ == "__main__":
    unittest.main()
